# Generated by Django 6.0.3 on 2026-03-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100, unique=True)),
                ('schedule', models.CharField(default='*/2 * * * *', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='DeployHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_type', models.CharField(default='manual', max_length=20)),
                ('prev_commit', models.CharField(blank=True, max_length=40, null=True)),
                ('new_commit', models.CharField(blank=True, max_length=40, null=True)),
                ('outcome', models.CharField(max_length=20)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('log_snippet', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
