# Generated by Django 6.0.3 on 2026-03-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('outcome', models.CharField(default='success', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('dbname', models.CharField(max_length=100)),
                ('schedule', models.CharField(default='0 2 * * *', max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('retention', models.IntegerField(default=7)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['project', 'dbname'],
                'unique_together': {('project', 'dbname')},
            },
        ),
    ]
